# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
User.create(username: "demoUser", password_digest: "$2a$12$JT98UKjUzhLIwE8Wbo3/EO.NRF43w9CT1b62c8ZSw7q6TR9uMIB8C", email: "demo@user.com", user_type: "fan")
kkb = User.create(username: "Kero Kero Bonito", password_digest: "$2a$12$JT98UKjUzhLIwE8Wbo3/EO.NRF43w9CT1b62c8ZSw7q6TR9uMIB8C", email: "kero@bonito.com", user_type: "artist")
bh = User.create(username: "Beach House", password_digest: "$2a$12$JT98UKjUzhLIwE8Wbo3/EO.NRF43w9CT1b62c8ZSw7q6TR9uMIB8C", email: "beach@house.com", user_type: "artist")
bloom = Album.create(artist_id: bh.id, title: "Bloom", release_date: Date.new(2012, 5, 15))
bloom_cover = open("https://socian-seed.s3-us-west-1.amazonaws.com/bloom.jpg")
bloom.cover.attach(io: bloom_cover, filename: "bloom.jpg")
Track.create(album_id: bloom.id, title: "Myth", length: "4:19")
Track.create(album_id: bloom.id, title: "Wild", length: "4:58")
Track.create(album_id: bloom.id, title: "Lazuli", length: "5:02")
Track.create(album_id: bloom.id, title: "Other People", length: "4:25")
Track.create(album_id: bloom.id, title: "The Hours", length: "4:12")
Track.create(album_id: bloom.id, title: "Troublemaker", length: "4:56")
Track.create(album_id: bloom.id, title: "New Year", length: "5:26")
Track.create(album_id: bloom.id, title: "Wishes", length: "4:47")
Track.create(album_id: bloom.id, title: "On The Sea", length: "5:32")
Track.create(album_id: bloom.id, title: "Irene", length: "16:57")
dc = Album.create(artist_id: bh.id, title: "Depression Cherry", release_date: Date.new(2015, 8, 28))
dc_cover = open("https://socian-seed.s3-us-west-1.amazonaws.com/depression_cherry.jpg")
dc.cover.attach(io: dc_cover, filename: "depression_cherry.jpg")
Track.create(album_id: bloom.id, title: "Levitation", length: "5:55")
Track.create(album_id: bloom.id, title: "Sparks", length: "5:21")
Track.create(album_id: bloom.id, title: "Space Song", length: "5:20")
Track.create(album_id: bloom.id, title: "Beyond Love", length: "4:25")
Track.create(album_id: bloom.id, title: "10:37", length: "3:49")
Track.create(album_id: bloom.id, title: "PPP", length: "6:09")
Track.create(album_id: bloom.id, title: "Wildflower", length: "3:39")
Track.create(album_id: bloom.id, title: "Bluebird", length: "3:55")
Track.create(album_id: bloom.id, title: "Days of Candy", length: "6:16")

bonito_generation = Album.create(artist_id: kkb.id, title: "Bonito Generation", release_date: Date.new(2016, 10, 21))
bonito_generation_cover = open("https://socian-seed.s3-us-west-1.amazonaws.com/bonito_generation.jpg")
bonito_generation.cover.attach(io: bonito_generation_cover, filename: "bonito_generation.jpg")
Track.create(album_id: bonito_generation.id, title: "Waking Up", length: "2:57")
Track.create(album_id: bonito_generation.id, title: "Heard A Song", length: "3:19")
Track.create(album_id: bonito_generation.id, title: "Graduation", length: "3:20")
Track.create(album_id: bonito_generation.id, title: "Fish Bowl", length: "1:46")
Track.create(album_id: bonito_generation.id, title: "Big City", length: "2:52")
Track.create(album_id: bonito_generation.id, title: "Break", length: "3:17")
Track.create(album_id: bonito_generation.id, title: "Lipslap", length: "3:40")
Track.create(album_id: bonito_generation.id, title: "Try Me", length: "3:30")
Track.create(album_id: bonito_generation.id, title: "Paintbrush", length: "0:57")
Track.create(album_id: bonito_generation.id, title: "Trampoline", length: "4:04")
Track.create(album_id: bonito_generation.id, title: "Picture This", length: "3:24")
Track.create(album_id: bonito_generation.id, title: "Hey Parents", length: "3:23")
flamingo = Album.create(artist_id: kkb.id, title: "Flamingo", release_date: Date.new(2014, 9, 23))
Track.create(album_id: flamingo.id, title: "Flamingo", length: "3:17")
flamingo_cover = open("https://socian-seed.s3-us-west-1.amazonaws.com/flamingo.jpg")
flamingo.cover.attach(io: flamingo_cover, filename: "flamingo.jpg")
time_n_place = Album.create(artist_id: kkb.id, title: "Time \'n\' Place", release_date: Date.new(2018, 10, 1))
time_n_place_cover = open("https://socian-seed.s3-us-west-1.amazonaws.com/time_'n'_place.jpg")
time_n_place.cover.attach(io: time_n_place_cover, filename: "time_n_place.jpg")





